name: Download Yu-Gi-Oh! Card Images

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download Yu-Gi-Oh! Card Images
        uses: ThatOneFrench/Yugioh-Artwork-Downloader@main
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          repository: ${{ github.repository }}
          image_directory: 'images'
